### PR TITLE
Allow kernels to be built from source

### PR DESCRIPTION
**Pull request by axxx007xxxz**

### CODE REVIEW

**Comment by axxx007xxxz** [comment]
Note: this change is untested.

**Comment by jerpelea** [comment]
if this git is not available the kernel is built from source!

**Comment by axxx007xxxz** [comment]
I know that, but it requires users to manually deleting it each time after a repo sync and/or adding it to remove-project entries in local_manifests.
Exporting a variable is better, in my opinion.

**Comment by jerpelea** [comment]
Development is done directly on github there may be bugs in the code.
Unless you are a kernel developper it is better to use the prebuilt snapshots which are tested

**Comment by MartinX3** [comment]
In which Intervall the prebuild kernels get refreshed?
Every month?
Milestone?

**Comment by jerpelea** [comment]
you have the log
usually every 7 days of there is something new

**Pull request closed without merging**
